export const CHIRO_PAIN_DIAGRAM_FORM = {
  id: 'chiro_pain_diagram',
  title: 'Pain Location & Symptoms',
  requiresSignature: false,
  intro: 'Please indicate the areas of your body where you are experiencing pain or symptoms.',
  sections: [
    {
      title: 'Pain Location',
      fields: [
        {
          id: 'painRegions',
          label: 'Mark all areas where you have pain or discomfort:',
          type: 'multicheck',
          required: true,
          options: [
            'Head / Skull',
            'Neck (cervical spine)',
            'Upper back / Between shoulder blades (thoracic)',
            'Mid back',
            'Lower back (lumbar)',
            'Tailbone / Sacrum / Pelvis',
            'Left shoulder',
            'Right shoulder',
            'Left arm / elbow',
            'Right arm / elbow',
            'Left wrist / hand / fingers',
            'Right wrist / hand / fingers',
            'Left hip / buttock',
            'Right hip / buttock',
            'Left thigh',
            'Right thigh',
            'Left knee',
            'Right knee',
            'Left lower leg / calf',
            'Right lower leg / calf',
            'Left foot / ankle / toes',
            'Right foot / ankle / toes',
            'Chest / Ribs',
            'Abdomen',
            'Jaw (TMJ)',
          ],
        },
        {
          id: 'primaryPainArea',
          label: 'Which area is bothering you the MOST?',
          type: 'text',
          required: false,
          placeholder: 'e.g., lower back, right shoulder...',
        },
      ],
    },
    {
      title: 'Symptom Type',
      fields: [
        {
          id: 'symptomTypes',
          label: 'What type of symptoms are you experiencing? (check all that apply)',
          type: 'multicheck',
          required: false,
          options: [
            'Pain', 'Stiffness / limited movement', 'Muscle weakness',
            'Numbness', 'Tingling / pins and needles', 'Burning sensation',
            'Clicking / popping joints', 'Swelling', 'Muscle spasm / tightness',
            'Headaches', 'Dizziness / balance problems',
          ],
        },
        {
          id: 'worstTimeOfDay',
          label: 'When is your pain WORST?',
          type: 'radio',
          required: false,
          options: [
            'Morning (after waking up)',
            'During the day with activity',
            'Evening / after work',
            'At night / while sleeping',
            'No clear pattern',
          ],
        },
        {
          id: 'overallFunction',
          label: 'On a scale of 0–10, how much does your pain limit your daily activities? (0 = no limitation, 10 = completely unable)',
          type: 'pain-slider',
          required: false,
        },
        {
          id: 'additionalSymptoms',
          label: 'Any other symptoms or concerns you would like your chiropractor to know?',
          type: 'textarea',
          required: false,
          placeholder: 'Any additional information...',
        },
      ],
    },
  ],
}
