export const CHIRO_HISTORY_FORM = {
  id: 'chiro_history',
  title: 'Back & Neck Pain Questionnaire',
  requiresSignature: false,
  sections: [
    {
      title: 'Chief Complaint',
      fields: [
        {
          id: 'chiefComplaint',
          label: 'What is your primary reason for visiting today?',
          type: 'textarea',
          required: true,
          placeholder: 'Describe your main concern, including location and nature of pain or discomfort...',
        },
        {
          id: 'onsetDate',
          label: 'When did this problem begin?',
          type: 'text',
          required: false,
          placeholder: 'e.g., 2 weeks ago, January 2024, gradually over the past year',
        },
        {
          id: 'mechanismOfInjury',
          label: 'How did this problem start?',
          type: 'radio',
          required: false,
          options: [
            'Auto accident',
            'Work injury',
            'Sports / recreational activity',
            'Slip & fall',
            'Gradual onset / no specific incident',
            'Unknown',
            'Other',
          ],
        },
        {
          id: 'mechanismDetails',
          label: 'Please describe what happened (if applicable)',
          type: 'textarea',
          required: false,
          placeholder: 'Briefly describe the incident or how the pain developed...',
        },
        {
          id: 'painScale',
          label: 'Current pain level (0 = no pain, 10 = worst pain imaginable)',
          type: 'pain-slider',
          required: false,
        },
        {
          id: 'painPattern',
          label: 'Is your pain:',
          type: 'radio',
          required: false,
          options: ['Constant', 'Intermittent (comes and goes)', 'Occasional'],
        },
      ],
    },
    {
      title: 'Pain Description',
      fields: [
        {
          id: 'painQuality',
          label: 'How would you describe your pain? (check all that apply)',
          type: 'multicheck',
          required: false,
          options: [
            'Sharp', 'Dull', 'Aching', 'Burning', 'Shooting', 'Stabbing',
            'Throbbing', 'Stiffness', 'Tingling', 'Numbness', 'Pressure', 'Weakness',
          ],
        },
        {
          id: 'radiating',
          label: 'Does the pain radiate or travel to other areas?',
          type: 'radio',
          required: false,
          options: ['Yes', 'No'],
        },
        {
          id: 'radiatingLocation',
          label: 'If yes, where does it radiate?',
          type: 'text',
          required: false,
          placeholder: 'e.g., down the left arm, into the buttock, down the leg to the foot...',
        },
        {
          id: 'aggravatingFactors',
          label: 'What makes the pain WORSE? (check all that apply)',
          type: 'multicheck',
          required: false,
          options: [
            'Sitting', 'Standing', 'Walking', 'Bending forward', 'Bending backward',
            'Twisting', 'Lifting', 'Lying down', 'Coughing / sneezing', 'Morning (after sleep)',
            'Physical activity', 'Stress',
          ],
        },
        {
          id: 'relievingFactors',
          label: 'What makes the pain BETTER? (check all that apply)',
          type: 'multicheck',
          required: false,
          options: [
            'Rest', 'Ice', 'Heat', 'Stretching', 'Exercise', 'Lying down',
            'Pain medication', 'Changing position', 'Walking', 'Nothing helps',
          ],
        },
      ],
    },
    {
      title: 'Functional Impact',
      fields: [
        {
          id: 'activitiesAffected',
          label: 'Which daily activities are affected by your condition? (check all that apply)',
          type: 'multicheck',
          required: false,
          options: [
            'Work / job duties', 'Driving', 'Sleeping', 'Dressing / personal care',
            'Household chores', 'Exercise / recreation', 'Sitting for extended periods',
            'Standing for extended periods', 'Social activities', 'None significantly affected',
          ],
        },
        {
          id: 'workStatus',
          label: 'Has this condition affected your ability to work?',
          type: 'radio',
          required: false,
          options: ['No', 'Working with limitations', 'Off work / on leave', 'Not currently employed'],
        },
      ],
    },
    {
      title: 'Prior Treatment',
      fields: [
        {
          id: 'previousTreatments',
          label: 'Have you received any treatment for this condition? (check all that apply)',
          type: 'multicheck',
          required: false,
          options: [
            'Chiropractic care', 'Physical therapy', 'Massage therapy', 'Acupuncture',
            'Medication (OTC)', 'Prescription medication', 'Injections (cortisone, epidural)',
            'Surgery', 'None',
          ],
        },
        {
          id: 'previousTreatmentResponse',
          label: 'How did you respond to previous treatment?',
          type: 'text',
          required: false,
          placeholder: 'e.g., helped temporarily, no effect, made it worse...',
        },
        {
          id: 'imagingDone',
          label: 'Have any of the following been done for this condition? (check all that apply)',
          type: 'multicheck',
          required: false,
          options: ['X-Ray', 'MRI', 'CT Scan', 'Ultrasound', 'None'],
        },
        {
          id: 'imagingResults',
          label: 'If yes, what were the findings?',
          type: 'text',
          required: false,
          placeholder: 'e.g., disc bulge at L4-L5, no significant findings...',
        },
        {
          id: 'previousChiropractic',
          label: 'Have you received chiropractic care in the past?',
          type: 'radio',
          required: false,
          options: ['Yes', 'No'],
        },
        {
          id: 'previousChiropracticDetails',
          label: 'If yes, when and how was your experience?',
          type: 'text',
          required: false,
          placeholder: 'Approximate dates and your response to care...',
        },
      ],
    },
    {
      title: 'Medical History',
      fields: [
        {
          id: 'currentMedications',
          label: 'Current Medications & Supplements',
          type: 'textarea',
          required: false,
          placeholder: 'List all medications, vitamins, and supplements including dosages...',
        },
        {
          id: 'allergies',
          label: 'Allergies (medications, foods, environmental)',
          type: 'textarea',
          required: false,
          placeholder: 'List all known allergies...',
        },
        {
          id: 'pastSurgeries',
          label: 'Past Surgeries or Hospitalizations',
          type: 'textarea',
          required: false,
          placeholder: 'Include type, area of body, and approximate date...',
        },
        {
          id: 'medicalConditions',
          label: 'Do you have any of the following conditions? (check all that apply)',
          type: 'multicheck',
          required: false,
          options: [
            'Osteoporosis / Osteopenia', 'Arthritis (osteoarthritis)', 'Rheumatoid Arthritis',
            'Herniated / Bulging Disc (known)', 'Spinal Stenosis', 'Scoliosis',
            'Fracture (recent or healing)', 'Cancer (current or history)',
            'Cardiovascular Disease / Heart Condition', 'High Blood Pressure',
            'Diabetes', 'Blood Clotting Disorder / Taking Blood Thinners',
            'Epilepsy / Seizures', 'Fibromyalgia', 'Anxiety / Depression',
            'None of the above',
          ],
        },
        {
          id: 'occupation',
          label: 'Occupation',
          type: 'text',
          required: false,
          placeholder: 'Your job or occupation',
        },
      ],
    },
  ],
}
