// All available built-in form templates
export const FORM_CATALOG = [
  {
    id: 'patient_info',
    title: 'Patient Information',
    category: 'common',
    categoryLabel: 'Common — All Clinics',
    description: 'Name, DOB, contact, address, emergency contact, insurance, referral source.',
    requiresSignature: false,
    required: true, // cannot be removed
  },
  {
    id: 'hipaa',
    title: 'HIPAA Notice of Privacy Practices',
    category: 'common',
    categoryLabel: 'Common — All Clinics',
    description: 'Federal HIPAA privacy rights disclosure with patient acknowledgment and signature.',
    requiresSignature: true,
    required: true,
  },
  {
    id: 'financial_policy',
    title: 'Financial Policy',
    category: 'common',
    categoryLabel: 'Common — All Clinics',
    description: 'Payment, cancellation, no-show, returned check, and insurance policies. Fees auto-filled from your settings.',
    requiresSignature: true,
    required: true,
  },
  {
    id: 'assignment_of_benefits',
    title: 'Assignment of Benefits',
    category: 'common',
    categoryLabel: 'Common — All Clinics',
    description: 'Authorizes direct insurance payment to your clinic.',
    requiresSignature: true,
    required: false,
  },
  {
    id: 'arbitration',
    title: 'Arbitration Agreement',
    category: 'common',
    categoryLabel: 'Common — All Clinics',
    description: 'Optional binding arbitration agreement. Patient may decline to sign.',
    requiresSignature: true,
    required: false,
    optional: true,
  },
  {
    id: 'information_release',
    title: 'Authorization to Release Medical Information',
    category: 'common',
    categoryLabel: 'Common — All Clinics',
    description: 'Authorizes release of medical records to attorneys, insurance companies, and other treating providers.',
    requiresSignature: true,
    required: false,
  },
  {
    id: 'acupuncture_consent',
    title: 'Acupuncture Informed Consent',
    category: 'acupuncture',
    categoryLabel: 'Acupuncture',
    description: 'Risks, benefits, alternatives, and consent for acupuncture and related treatments.',
    requiresSignature: true,
    required: false,
  },
  {
    id: 'health_history',
    title: 'Health History & Chief Complaint',
    category: 'acupuncture',
    categoryLabel: 'Acupuncture',
    description: 'Chief complaint, pain scale, medical history, medications, allergies, lifestyle, and women\'s health.',
    requiresSignature: false,
    required: false,
  },
  {
    id: 'review_of_systems',
    title: 'Review of Systems',
    category: 'acupuncture',
    categoryLabel: 'Acupuncture',
    description: 'Comprehensive symptom checklist across neurological, musculoskeletal, cardiovascular, digestive, mental health, and more.',
    requiresSignature: false,
    required: false,
  },
  {
    id: 'chiro_consent',
    title: 'Chiropractic Informed Consent',
    category: 'chiropractic',
    categoryLabel: 'Chiropractic',
    description: 'Risks, benefits, and consent for chiropractic adjustments and related treatments.',
    requiresSignature: true,
    required: false,
  },
  {
    id: 'chiro_pain_diagram',
    title: 'Pain Location & Symptoms',
    category: 'chiropractic',
    categoryLabel: 'Chiropractic',
    description: 'Pain region selection, symptom type checklist, and functional impact scale.',
    requiresSignature: false,
    required: false,
  },
  {
    id: 'chiro_history',
    title: 'Back & Neck Pain Questionnaire',
    category: 'chiropractic',
    categoryLabel: 'Chiropractic',
    description: 'Chief complaint, mechanism of injury, pain quality, functional impact, and medical history.',
    requiresSignature: false,
    required: false,
  },
  {
    id: 'massage_consent',
    title: 'Massage Therapy Consent',
    category: 'massage',
    categoryLabel: 'Massage Therapy',
    description: 'Consent form covering massage techniques, pressure preferences, and contraindications.',
    requiresSignature: true,
    required: false,
    comingSoon: true,
  },
  {
    id: 'massage_intake',
    title: 'Massage Health Intake & Contraindications',
    category: 'massage',
    categoryLabel: 'Massage Therapy',
    description: 'Health history focused on contraindications, skin conditions, medications, and goals.',
    requiresSignature: false,
    required: false,
    comingSoon: true,
  },
  {
    id: 'pi_auto_accident',
    title: 'Auto Accident / PI Intake',
    category: 'pi',
    categoryLabel: 'Personal Injury',
    description: 'Detailed accident information: vehicle details, impact, symptoms, prior history, attorney and insurance information.',
    requiresSignature: false,
    required: false,
  },
  {
    id: 'pi_medical_lien',
    title: 'Medical Lien Agreement',
    category: 'pi',
    categoryLabel: 'Personal Injury',
    description: 'Patient assigns rights to collect treatment fees from settlement or judgment proceeds.',
    requiresSignature: true,
    required: false,
  },
]

export const CATEGORY_ORDER = ['common', 'acupuncture', 'chiropractic', 'pi', 'massage']
export const CATEGORY_COLORS = {
  common: 'bg-blue-50 text-blue-700 border-blue-200',
  acupuncture: 'bg-blue-50 text-blue-700 border-blue-200',
  chiropractic: 'bg-orange-50 text-orange-700 border-orange-200',
  pi: 'bg-amber-50 text-amber-700 border-amber-200',
  massage: 'bg-pink-50 text-pink-700 border-pink-200',
  custom: 'bg-purple-50 text-purple-700 border-purple-200',
}

export const CATEGORY_META = {
  common:        { label: 'Common — All Clinics', collapsible: false, comingSoon: false },
  acupuncture:   { label: 'Acupuncture',          collapsible: true,  comingSoon: false },
  chiropractic:  { label: 'Chiropractic',         collapsible: true,  comingSoon: false },
  pi:            { label: 'Personal Injury',      collapsible: true,  comingSoon: false },
  massage:       { label: 'Massage Therapy',      collapsible: true,  comingSoon: true  },
}

export const DEFAULT_FORM_IDS = [
  'patient_info',
  'hipaa',
  'financial_policy',
  'assignment_of_benefits',
  'arbitration',
]
